version: '3.8'

services:
  app:
    build: .
    restart: always
    ports:
      - "4321:4321"
    environment:
      - HOST=0.0.0.0
      - PORT=4321
      - NODE_ENV=production
      # Configuración de Base de Datos
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      # Configuración de Autenticación
      - JWT_SECRET=${JWT_SECRET}

      # URL Base de la aplicación
      - APP_BASE_URL=${APP_BASE_URL}
    volumes:
      # Persistencia opcional para uploads locales (si fuera necesario)
      - ./uploads:/app/uploads
